// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnYCzB7HiCJItBiaHVYUchttw1HWVBuK4',
    appId: '1:873067650643:web:c6e4327a7f71f22db3b0a6',
    messagingSenderId: '873067650643',
    projectId: 'ordersservice-af96d',
    authDomain: 'ordersservice-af96d.firebaseapp.com',
    storageBucket: 'ordersservice-af96d.appspot.com',
    measurementId: 'G-0ZBMK1J8GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs1LWas-Ln1J3q1-G0ZCeJU57KtdeusLY',
    appId: '1:873067650643:android:efa5aae3ca03621eb3b0a6',
    messagingSenderId: '873067650643',
    projectId: 'ordersservice-af96d',
    storageBucket: 'ordersservice-af96d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzevDC_pmSRCdRvVOQYQc3qODU68MHqww',
    appId: '1:873067650643:ios:e944966fe6f670cdb3b0a6',
    messagingSenderId: '873067650643',
    projectId: 'ordersservice-af96d',
    storageBucket: 'ordersservice-af96d.appspot.com',
    iosBundleId: 'com.example.raktaWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzevDC_pmSRCdRvVOQYQc3qODU68MHqww',
    appId: '1:873067650643:ios:0bb6836a8d0530bab3b0a6',
    messagingSenderId: '873067650643',
    projectId: 'ordersservice-af96d',
    storageBucket: 'ordersservice-af96d.appspot.com',
    iosBundleId: 'com.example.raktaWeb.RunnerTests',
  );
}
